/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

/**
 *
 * @author Mauro
 */
public class vtnPrincipal extends javax.swing.JFrame
{

    /**
     * Creates new form NewJFrame
     */
    public vtnPrincipal()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel3 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();
        btnRecibir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnBandejaEntrada = new javax.swing.JButton();
        btnEliminados = new javax.swing.JButton();
        btnSpameados = new javax.swing.JButton();
        btnEnviados = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanelPrincipal = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        txtGmail = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Control de cuentas de correo");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Herramientas"));

        txtBuscar.setEnabled(false);

        btnBuscar.setText("Buscar");
        btnBuscar.setEnabled(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEnviar.setText("Enviar");
        btnEnviar.setEnabled(false);
        btnEnviar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEnviarActionPerformed(evt);
            }
        });

        btnRecibir.setText("Recibir");
        btnRecibir.setEnabled(false);
        btnRecibir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRecibirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEnviar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRecibir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnRecibir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        btnBandejaEntrada.setText("Bandeja de entrada");
        btnBandejaEntrada.setEnabled(false);
        btnBandejaEntrada.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBandejaEntradaActionPerformed(evt);
            }
        });

        btnEliminados.setText("Eliminados");
        btnEliminados.setEnabled(false);
        btnEliminados.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEliminadosActionPerformed(evt);
            }
        });

        btnSpameados.setText("Spam");
        btnSpameados.setEnabled(false);
        btnSpameados.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSpameadosActionPerformed(evt);
            }
        });

        btnEnviados.setText("Enviados");
        btnEnviados.setEnabled(false);
        btnEnviados.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEnviadosActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBandejaEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(btnEliminados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSpameados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEnviados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnSalir)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnBandejaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminados, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSpameados, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEnviados, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder("Bandeja de Entrada"));
        jPanelPrincipal.setLayout(new java.awt.GridLayout(0, 1, 20, 20));
        jScrollPane2.setViewportView(jPanelPrincipal);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUsuario)
                    .addComponent(txtGmail, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 450, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtGmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGuardar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE)
                        .addGap(4, 4, 4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBuscarActionPerformed
    {//GEN-HEADEREND:event_btnBuscarActionPerformed

        jPanelPrincipal.removeAll();
        Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
            + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        String gmail = txtBuscar.getText();
        Matcher mather = pattern.matcher(gmail);;
        if (mather.find())
        {
            boolean ban = false;
            if (buscar(general.getBandejaEntrada(), gmail))
            {
                jPanelPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder("Bandeja de entrada"));
                ban = true;
            } else
            {
                if (buscar(general.getElimados(), gmail))
                {
                    jPanelPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder("Eliminados"));
                    ban = true;
                } else
                {
                    if (buscar(general.getEnviados(), gmail))
                    {
                        jPanelPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder("Enviados"));
                        ban = true;
                    } else
                    {
                        if (buscar(general.getSpam(), gmail))
                        {
                            jPanelPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder("Spam"));
                            ban = true;
                        } else
                        {
                            JLabel mensaje = new JLabel("No hay concidencias");
                            jPanelPrincipal.add(mensaje);
                        }
                    }
                }
            }
            if (ban)
            {
                JButton boton = new JButton((1) + " :" + encontrado.getObj().getCorreoOrigen() + "->" + encontrado.getObj().getCorreoDestino());
                boton.setMaximumSize(new Dimension(50, 16));
                boton.setMinimumSize(new Dimension(20, 20));
                boton.setPreferredSize(new Dimension(120, 30));
                jPanelPrincipal.add(boton);
                boton.addActionListener(new ActionListener()
                    {
                        @Override
                        public void actionPerformed(ActionEvent e)
                        {
                            new VerCorreo(null, true, encontrado).setVisible(true);
                        }
                    });
                }
            } else
            {
                txtBuscar.setText("");
            }
            jPanelPrincipal.updateUI();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEnviarActionPerformed
    {//GEN-HEADEREND:event_btnEnviarActionPerformed
        new EnviarCorreo().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnRecibirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRecibirActionPerformed
    {//GEN-HEADEREND:event_btnRecibirActionPerformed
        new RecibirCorreo().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRecibirActionPerformed

    private void btnBandejaEntradaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBandejaEntradaActionPerformed
    {//GEN-HEADEREND:event_btnBandejaEntradaActionPerformed
        jPanelPrincipal.removeAll();
        jPanelPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder("Bandeja de entrada"));

        if (general.getBandejaEntrada().getCantidad() > 0)
        {
            PilasD tmp = new PilasD();
            int ca = general.getBandejaEntrada().getCantidad();
            for (int i = 0; i < ca; i++)
            {
                Nodo tmpn = general.getBandejaEntrada().elimina();
                System.out.println(tmpn.getObj().getCorreoOrigen());
                JButton boton = new JButton((i + 1) + " :" + tmpn.getObj().getCorreoOrigen() + "->" + tmpn.getObj().getCorreoDestino());
                boton.setMaximumSize(new Dimension(50, 16));
                boton.setMinimumSize(new Dimension(20, 20));
                boton.setPreferredSize(new Dimension(120, 30));
                jPanelPrincipal.add(boton);
                tmp.inserta(tmpn);

                boton.addActionListener(new ActionListener()
                    {
                        @Override
                        public void actionPerformed(ActionEvent e)
                        {
                            jPanelPrincipal.updateUI();
                            new vtnMiniMenu(null, true, tmpn, 1).setVisible(true);
                        }
                    });
                }
                ca = tmp.getCantidad();
                for (int i = 0; i < ca; i++)
                {
                    general.getBandejaEntrada().inserta(tmp.elimina());
                }
                jPanelPrincipal.updateUI();
            }
    }//GEN-LAST:event_btnBandejaEntradaActionPerformed

    private void btnEliminadosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEliminadosActionPerformed
    {//GEN-HEADEREND:event_btnEliminadosActionPerformed
        jPanelPrincipal.removeAll();
        jPanelPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder("Eliminados"));
        if (general.getElimados().getTope() != null)
        {
            PilasD tmp = new PilasD();
            int ca = general.getElimados().getCantidad();
            for (int i = 0; i < ca; i++)
            {
                Nodo tmpn = general.getElimados().elimina();
                JButton boton = new JButton((i + 1) + " :" + tmpn.getObj().getCorreoOrigen() + "->" + tmpn.getObj().getCorreoDestino());
                boton.setMaximumSize(new Dimension(50, 16));
                boton.setMinimumSize(new Dimension(20, 20));
                boton.setPreferredSize(new Dimension(120, 30));
                jPanelPrincipal.add(boton);
                tmp.inserta(tmpn);

                boton.addActionListener(new ActionListener()
                    {
                        @Override
                        public void actionPerformed(ActionEvent e)
                        {
                            new VerCorreo(null, true, tmpn).setVisible(true);
                        }
                    });

                    System.out.println(i);
                }
                ca = tmp.getCantidad();
                for (int i = 0; i < tmp.getCantidad(); i++)
                {
                    general.getElimados().inserta(tmp.elimina());
                }
                jPanelPrincipal.updateUI();
            }
    }//GEN-LAST:event_btnEliminadosActionPerformed

    private void btnSpameadosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSpameadosActionPerformed
    {//GEN-HEADEREND:event_btnSpameadosActionPerformed
        jPanelPrincipal.removeAll();
        jPanelPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder("Spam"));

        if (general.getSpam().getTope() != null)
        {
            PilasD tmp = new PilasD();
            int ca = general.getSpam().getCantidad();
            for (int i = 0; i < ca; i++)
            {
                Nodo tmpn = general.getSpam().elimina();
                JButton boton = new JButton((i + 1) + " :" + tmpn.getObj().getCorreoOrigen() + "->" + tmpn.getObj().getCorreoDestino());
                boton.setMaximumSize(new Dimension(50, 16));
                boton.setMinimumSize(new Dimension(20, 20));
                boton.setPreferredSize(new Dimension(120, 30));
                jPanelPrincipal.add(boton);
                tmp.inserta(tmpn);
                boton.addActionListener(new ActionListener()
                    {
                        @Override
                        public void actionPerformed(ActionEvent e)
                        {
                            new VerCorreo(null, true, tmpn).setVisible(true);
                        }
                    });
                    System.out.println(i);
                }
                ca = tmp.getCantidad();
                for (int i = 0; i < ca; i++)
                {
                    general.getSpam().inserta(tmp.elimina());
                }
                jPanelPrincipal.updateUI();
            }
    }//GEN-LAST:event_btnSpameadosActionPerformed

    private void btnEnviadosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEnviadosActionPerformed
    {//GEN-HEADEREND:event_btnEnviadosActionPerformed
        jPanelPrincipal.removeAll();
        jPanelPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder("Enviados"));

        if (general.getEnviados().getTope() != null)
        {
            PilasD tmp = new PilasD();
            int ca = general.getEnviados().getCantidad();
            for (int i = 0; i < ca; i++)
            {
                Nodo tmpn = general.getEnviados().elimina();
                JButton boton = new JButton((i + 1) + " :" + tmpn.getObj().getCorreoOrigen() + "->" + tmpn.getObj().getCorreoDestino());
                boton.setMaximumSize(new Dimension(50, 16));
                boton.setMinimumSize(new Dimension(20, 20));
                boton.setPreferredSize(new Dimension(120, 30));
                jPanelPrincipal.add(boton);
                tmp.inserta(tmpn);
                boton.addActionListener(new ActionListener()
                    {
                        @Override
                        public void actionPerformed(ActionEvent e)
                        {
                            jPanelPrincipal.updateUI();
                            new vtnMiniMenu(null, true, tmpn, 2).setVisible(true);
                        }
                    });
                    System.out.println(i);
                }
                ca = tmp.getCantidad();
                for (int i = 0; i < ca; i++)
                {
                    general.getEnviados().inserta(tmp.elimina());
                }
                jPanelPrincipal.updateUI();
            }

    }//GEN-LAST:event_btnEnviadosActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSalirActionPerformed
    {//GEN-HEADEREND:event_btnSalirActionPerformed
        try
        {
            ObjectOutputStream archivo = new ObjectOutputStream(new FileOutputStream("datos.dat"));
            archivo.writeObject(general);
            archivo.close();
        } catch (Exception e)
        {
            System.out.println("No existe el archivo");
        }

        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGuardarActionPerformed
    {//GEN-HEADEREND:event_btnGuardarActionPerformed
        Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
            + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        String gmail = "";
        gmail = txtGmail.getText();
        Matcher mather = pattern.matcher(gmail);
        if (mather.find())
        {
            general.setCorreoOrigen(gmail);
            general.setNombre(txtUsuario.getText());
            txtUsuario.setText(general.getNombre());
            txtGmail.setText(general.getCorreoOrigen());
            txtBuscar.setEnabled(true);
            btnBuscar.setEnabled(true);
            btnBandejaEntrada.setEnabled(true);
            btnEliminados.setEnabled(true);
            btnEnviados.setEnabled(true);
            btnEnviar.setEnabled(true);
            btnRecibir.setEnabled(true);
            btnSpameados.setEnabled(true);
            txtGmail.setEditable(false);
            txtUsuario.setEditable(false);
            btnGuardar.setEnabled(false);
        } else
        {
            txtGmail.setText("");
            txtUsuario.setText("");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(vtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(vtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(vtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(vtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new vtnPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBandejaEntrada;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminados;
    private javax.swing.JButton btnEnviados;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRecibir;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSpameados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtGmail;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
